version: '3.8'

networks:
  50brains-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:

services:
  # =============================================================================
  # INFRASTRUCTURE SERVICES
  # =============================================================================
  
  redis:
    image: redis:7-alpine
    container_name: 50brains-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - 50brains-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    networks:
      - 50brains-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

  # =============================================================================
  # APPLICATION SERVICES
  # =============================================================================